### ISSUE TITLE
你好，能否提供一下netlify的一键部署渠道

### ISSUE THREAD

**Issue by Crash2333** [weekend-project-space/e9x-fun#3]
你好，能否提供一下netlify的一键部署渠道。
非常感谢！！！

**Comment by Crash2333** [comment]
直接fork之后，登录netlify。
在netlify选择GitHub仓库部署，选择fork的库即可。

当然，如果作者能提供一键部署。会更方便些。

**Comment by weekend-project-space** [comment]
> 直接fork之后，登录netlify。 在netlify中选择GitHub仓库部署，选择fork的库即可。
> 
> 当然，如果作者能够提供一键部署。会更方便一些。

可以 fork 更新readme 文件
